image: go-1.19

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

job:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go

      - name: Checkout code into the Go module repository
        uses: actions/checkout@v2

      - name: Test
        run: make test